### ISSUE TITLE
Mod works but skill does nothing

### ISSUE THREAD

**Issue by Thaumatarge** [blaxxun-boop/Vitality#1]
I do not know if the mod works as intended, but my base health is not increasing as Vitality increases, despite the skill being present. I am running the Public Test version of Valheim, so it might be the culprit, however every other skill like Pack Horse, Blacksmithing, and Cooking work just fine, so I am uncertain.

**Comment by Thaumatarge** [comment]
I have figured what the problem seems to be, and that is that it doesn't update immediately.

**Comment by blaxxun-boop** [comment]
You probably just have a mod that overrides your health and isn't compatible with other mods touching the players health.
