### ISSUE TITLE
Skill doesn't seem to work properly

### ISSUE THREAD

**Issue by Condemnedfate** [blaxxun-boop/Vitality#2]
I don't know if I misunderstood the mod description or if the mod doesn't work as intended. No matter what I only have the default base health of 25. The skill does level up but it doesn't raise my max base health. Is this mod only intended to work so long as you have food in your foodbar?

**Comment by blaxxun-boop** [comment]
You probably just have a mod that overrides your health and isn't compatible with other mods touching the players health.
